name: C/C++ CI

on: [push]

jobs:
  UnixBuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: cmake -B build ; cd /home/runner/work/ToyRobot/ToyRobot/build ; make -j40
    - name: Test
      run: /home/runner/work/ToyRobot/ToyRobot/build/test

  WindowsBuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: microsoft/setup-msbuild@v1
      - name: Configure
        run: cmake -B build -G "MinGW Makefiles" ; cd build ; make
      - name: Test
        run: dir ; cd build ; dir
