name: C/C++ CI

on: [push]

jobs:
  UnixBuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: cmake -B build ; cd /home/runner/work/ToyRobot/ToyRobot/build ; make -j40
    - name: Test
      run: /home/runner/work/ToyRobot/ToyRobot/build/test

  WindowsBuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: microsoft/setup-msbuild@v1
      - name: Setup
        run : call C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
      - name: Configure
        run: cmake -B build -G "NMake Makefiles" ; cd build ; nmake
